#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libthai
Version  : 0.1.28
Release  : 8
URL      : ftp://linux.thai.net/pub/thailinux/software/libthai/libthai-0.1.28.tar.xz
Source0  : ftp://linux.thai.net/pub/thailinux/software/libthai/libthai-0.1.28.tar.xz
Summary  : Thai support library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libthai-data = %{version}-%{release}
Requires: libthai-lib = %{version}-%{release}
Requires: libthai-license = %{version}-%{release}
BuildRequires : doxygen
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkg-config
BuildRequires : pkgconfig(32datrie-0.2)
BuildRequires : pkgconfig(datrie-0.2)

%description
General Information
===================
LibThai is a set of Thai language support routines aimed to ease
developers' tasks to incorporate Thai language support in their
applications. It includes important Thai-specific functions e.g. word
breaking, input and output methods as well as basic character and
string supports. LibThai is an Open Source and collaborative effort
initiated by Thai Linux Working Group and opened for all contributors.

%package data
Summary: data components for the libthai package.
Group: Data

%description data
data components for the libthai package.


%package dev
Summary: dev components for the libthai package.
Group: Development
Requires: libthai-lib = %{version}-%{release}
Requires: libthai-data = %{version}-%{release}
Provides: libthai-devel = %{version}-%{release}
Requires: libthai = %{version}-%{release}

%description dev
dev components for the libthai package.


%package dev32
Summary: dev32 components for the libthai package.
Group: Default
Requires: libthai-lib32 = %{version}-%{release}
Requires: libthai-data = %{version}-%{release}
Requires: libthai-dev = %{version}-%{release}

%description dev32
dev32 components for the libthai package.


%package doc
Summary: doc components for the libthai package.
Group: Documentation

%description doc
doc components for the libthai package.


%package lib
Summary: lib components for the libthai package.
Group: Libraries
Requires: libthai-data = %{version}-%{release}
Requires: libthai-license = %{version}-%{release}

%description lib
lib components for the libthai package.


%package lib32
Summary: lib32 components for the libthai package.
Group: Default
Requires: libthai-data = %{version}-%{release}
Requires: libthai-license = %{version}-%{release}

%description lib32
lib32 components for the libthai package.


%package license
Summary: license components for the libthai package.
Group: Default

%description license
license components for the libthai package.


%prep
%setup -q -n libthai-0.1.28
pushd ..
cp -a libthai-0.1.28 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1569530452
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check
cd ../build32;
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1569530452
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libthai
cp COPYING %{buildroot}/usr/share/package-licenses/libthai/COPYING
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/libthai/thbrk.tri

%files dev
%defattr(-,root,root,-)
/usr/include/thai/thailib.h
/usr/include/thai/thbrk.h
/usr/include/thai/thcell.h
/usr/include/thai/thcoll.h
/usr/include/thai/thctype.h
/usr/include/thai/thinp.h
/usr/include/thai/thrend.h
/usr/include/thai/thstr.h
/usr/include/thai/thwbrk.h
/usr/include/thai/thwchar.h
/usr/include/thai/thwcoll.h
/usr/include/thai/thwctype.h
/usr/include/thai/thwinp.h
/usr/include/thai/thwrend.h
/usr/include/thai/thwstr.h
/usr/include/thai/tis.h
/usr/include/thai/wtt.h
/usr/lib64/libthai.so
/usr/lib64/pkgconfig/libthai.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libthai.so
/usr/lib32/pkgconfig/32libthai.pc
/usr/lib32/pkgconfig/libthai.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libthai/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libthai.so.0
/usr/lib64/libthai.so.0.3.1

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libthai.so.0
/usr/lib32/libthai.so.0.3.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libthai/COPYING
