#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libthai
Version  : 0.1.26
Release  : 2
URL      : ftp://linux.thai.net/pub/thailinux/software/libthai/libthai-0.1.26.tar.xz
Source0  : ftp://linux.thai.net/pub/thailinux/software/libthai/libthai-0.1.26.tar.xz
Summary  : Thai support library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libthai-lib
Requires: libthai-data
Requires: libthai-doc
BuildRequires : doxygen
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(32datrie-0.2)
BuildRequires : pkgconfig(datrie-0.2)

%description
General Information
===================
LibThai is a set of Thai language support routines aimed to ease
developers' tasks to incorporate Thai language support in their
applications. It includes important Thai-specific functions e.g. word
breaking, input and output methods as well as basic character and
string supports. LibThai is an Open Source and collaborative effort
initiated by Thai Linux Working Group and opened for all contributors.

%package data
Summary: data components for the libthai package.
Group: Data

%description data
data components for the libthai package.


%package dev
Summary: dev components for the libthai package.
Group: Development
Requires: libthai-lib
Requires: libthai-data
Provides: libthai-devel

%description dev
dev components for the libthai package.


%package dev32
Summary: dev32 components for the libthai package.
Group: Default
Requires: libthai-lib32
Requires: libthai-data
Requires: libthai-dev

%description dev32
dev32 components for the libthai package.


%package doc
Summary: doc components for the libthai package.
Group: Documentation

%description doc
doc components for the libthai package.


%package lib
Summary: lib components for the libthai package.
Group: Libraries
Requires: libthai-data

%description lib
lib components for the libthai package.


%package lib32
Summary: lib32 components for the libthai package.
Group: Default
Requires: libthai-data

%description lib32
lib32 components for the libthai package.


%prep
%setup -q -n libthai-0.1.26
pushd ..
cp -a libthai-0.1.26 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1494255179
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1494255179
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/libthai/thbrk.tri

%files dev
%defattr(-,root,root,-)
/usr/include/thai/thailib.h
/usr/include/thai/thbrk.h
/usr/include/thai/thcell.h
/usr/include/thai/thcoll.h
/usr/include/thai/thctype.h
/usr/include/thai/thinp.h
/usr/include/thai/thrend.h
/usr/include/thai/thstr.h
/usr/include/thai/thwbrk.h
/usr/include/thai/thwchar.h
/usr/include/thai/thwcoll.h
/usr/include/thai/thwctype.h
/usr/include/thai/thwinp.h
/usr/include/thai/thwrend.h
/usr/include/thai/thwstr.h
/usr/include/thai/tis.h
/usr/include/thai/wtt.h
/usr/lib64/libthai.so
/usr/lib64/pkgconfig/libthai.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libthai.so
/usr/lib32/pkgconfig/32libthai.pc
/usr/lib32/pkgconfig/libthai.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libthai/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libthai.so.0
/usr/lib64/libthai.so.0.3.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libthai.so.0
/usr/lib32/libthai.so.0.3.0
